databases:
  - name: skavoca-db
    plan: free
    databaseName: skavoca
    region: singapore

services:
  - type: web
    name: skavoca-api
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    plan: free
    region: singapore
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: skavoca-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: skavoca-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: skavoca-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: skavoca-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: skavoca-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://skavoca-skala.vercel.app,https://app-eta-ecru-79.vercel.app
