spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      continue-on-error: true

jwt:
  secret: ${JWT_SECRET:skavoca-super-secret-key-for-jwt-token-generation-2026-must-be-256-bits-long}
  access-expiration: 1800000
  refresh-expiration: 604800000
