spring:
  application:
    name: skavoca-server
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/skavoca
    driver-class-name: org.postgresql.Driver
    username: jin
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never

server:
  port: 8080

jwt:
  secret: skavoca-super-secret-key-for-jwt-token-generation-2026-must-be-256-bits-long
  access-expiration: 1800000
  refresh-expiration: 604800000
